@startuml (TO-BE) Call Center Deposit Rates Integration Container Diagram
title (TO-BE) Call Center Deposit Rates Integration Container Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(call_center_employee, "Сотрудник кол-центра")
Person(partner_call_center_employee, "Сотрудник партнерского кол-центра")
Person(back_office, "Сотрудник бэк-офиса")

System_Ext(call_center_system, "Система кол-центра", "Java Spring Boot")
System_Ext(partner_call_center_system, "Система партнерского кол-центра")

System_Boundary(c1, "Сервис депозитных заявок") {
    Container(api, "API-приложение", "Java, Spring Boot", "Обрабатывает заявки и управляет ставками")
    Container(rates_api, "Rates API", "Java, Spring Boot", "Предоставляет актуальные ставки по REST API")
    Container(file_generator, "Генератор файлов ставок", "Java, Spring Boot", "Формирует файлы со ставками для партнеров")
    ContainerDb(db, "База данных", "PostgreSQL", "Хранит заявки и актуальные ставки")
}

ContainerDb(sftp_server, "SFTP-сервер", "Linux + OpenSSH", "Сервер для обмена файлами")

Rel(call_center_employee, call_center_system, "Консультирует клиентов")
Rel(partner_call_center_employee, partner_call_center_system, "Консультирует клиентов")

Rel(call_center_system, rates_api, "Запрашивает актуальные ставки", "HTTPS/REST")
Rel(rates_api, db, "Читает ставки", "JDBC")

Rel(back_office, api, "Обновляет ставки", "Excel/Email")
Rel(api, db, "Обновляет ставки", "JDBC")

Rel(file_generator, db, "Читает ставки", "JDBC")
Rel(file_generator, sftp_server, "Загружает файлы", "SFTP")
Rel(partner_call_center_system, sftp_server, "Скачивает файлы", "SFTP")

@enduml