@startuml
title (TO-BE) Standart Deposit Container Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, "Клиент")

System_Ext(site, "Сайт", "PHP, React.js")
System_Ext(ib, "Интернет-банк", "ASP.NET")
System_Ext(call_center_system, "Система кол-центра")
System_Ext(abs, "АБС", "Delphi, Oracle")

System_Boundary(c1, "Сервис депозитных заявок") {
    Container(api, "API-приложение", "Java, Spring Boot", "Принимает, валидирует и сохраняет заявки")
    ContainerDb(db, "База данных заявок", "PostgreSQL", "Хранит все онлайн-заявки")
}

ContainerDb(staging_db, "Промежуточная БД", "MS SQL", "Таблица для асинхронной передачи заявок в АБС")

Rel(client, site, "Подает заявку")
Rel(client, ib, "Подает заявку")

Rel(site, api, "Отправляет заявку", "JSON/HTTPS")
Rel(ib, api, "Отправляет заявку", "JSON/HTTPS")

Rel(api, db, "Сохраняет/Читает заявку", "JDBC")
Rel(api, call_center_system, "Создает обращение", "API")
Rel(api, staging_db, "Записывает заявку для АБС", "JDBC")

Rel(abs, staging_db, "Читает новые заявки (batch job)", "DB Link / ETL")

@enduml